# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27bd493abb5f1e5447bd8a630f162b315d869c8286b6a3862efead824871d5997148dcdf3201df1f446d3af7a02df301812f4c49729214ccefd5f3cbaec5060

test:
  secret_key_base: ba70b90b526a8631d706175a836f287fe546126042e1b1bf467a27fccb7587db922de2fdd72284da8371729b9e4e49cfca24bf6c59e3cfa5bf1708827a392662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
